"""Add google oauth tokens to users

Revision ID: 318df116df93
Revises: 4fb779d1d77f
Create Date: 2026-09-18 03:09:47.156874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318df116df93'
down_revision: Union[str, None] = '4fb779d1d77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_access_token', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    # ### end Alembic commands ###
