"""Add graph_preferences table

Revision ID: dab1594226d0
Revises: 60251de2be57
Create Date: 2026-09-15 10:41:41.127145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab1594226d0'
down_revision: Union[str, None] = '60251de2be57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('layout_type', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_preferences_id'), 'graph_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_graph_preferences_user_id'), 'graph_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_preferences_user_id'), table_name='graph_preferences')
    op.drop_index(op.f('ix_graph_preferences_id'), table_name='graph_preferences')
    op.drop_table('graph_preferences')
    # ### end Alembic commands ###
