"""Add Hermes Agent Models

Revision ID: dd0a92fbd0e9
Revises: 318df116df93
Create Date: 2026-09-18 03:25:55.812054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0a92fbd0e9'
down_revision: Union[str, None] = '318df116df93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('proposal_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=True),
    sa.Column('target_context_id', sa.Integer(), nullable=True),
    sa.Column('affects_person_id', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affects_person_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_context_id'], ['contexts.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_proposals_id'), 'agent_proposals', ['id'], unique=False)
    op.create_table('triples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('subject_entity_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('object_entity_id', sa.Integer(), nullable=True),
    sa.Column('object_literal', sa.String(length=255), nullable=True),
    sa.Column('info_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_agent', sa.String(length=50), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triples_id'), 'triples', ['id'], unique=False)
    op.add_column('contexts', sa.Column('info_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contexts', sa.Column('info_date_source', sa.String(length=50), nullable=True))
    op.add_column('contexts', sa.Column('revision', sa.Integer(), nullable=True))
    op.add_column('contexts', sa.Column('source_agent', sa.String(length=50), nullable=True))
    op.add_column('entities', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entities', sa.Column('info_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entities', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('entities', sa.Column('external_enrichment_opt_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'external_enrichment_opt_in')
    op.drop_column('entities', 'confidence')
    op.drop_column('entities', 'info_date')
    op.drop_column('entities', 'last_verified_at')
    op.drop_column('contexts', 'source_agent')
    op.drop_column('contexts', 'revision')
    op.drop_column('contexts', 'info_date_source')
    op.drop_column('contexts', 'info_date')
    op.drop_index(op.f('ix_triples_id'), table_name='triples')
    op.drop_table('triples')
    op.drop_index(op.f('ix_agent_proposals_id'), table_name='agent_proposals')
    op.drop_table('agent_proposals')
    # ### end Alembic commands ###
